FROM gcc:latest

WORKDIR /app

COPY . .

RUN chmod +x bootstrap.sh
RUN apt-get update && apt-get install -y \
    libjson-c-dev \
    libpq-dev    

RUN chmod +x wait-for-it.sh

    
CMD ["/bin/bash", "bootstrap.sh"]