version: '3.5'

services:
  api01: &api
    image: http-server
    hostname: api01
    ports:
      - "8080:8080"
    depends_on: # The api waits until the database is fully initialized
      - database
    links:
      - database
    entrypoint: ["./wait-for-it.sh", "database:5432", "--", "./bootstrap.sh"] # REVIEW - Check if PROD var is working
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8081:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "9999:9999"
    depends_on:
      - api01
      - api02
      - database
    links:
      - api01
      - api02
      - database
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "40MB"

  database:
    image: postgres:latest
    hostname: database
    environment:
      - POSTGRES_PASSWORD=rinha_pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_rinha
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./database/logs:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1