version: '3.5'

services:
  api: 
    image: http-server
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  database:
    image: postgres:latest
    hostname: database
    environment:
      - POSTGRES_PASSWORD=rinha_pass
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"