version: '3.5'

services:
  api: 
    image: http-server
    ports:
      - "8080:8080"
    depends_on: # The api waits until the database is fully initialized
      - database
    links:
      - database
    entrypoint: ["./wait-for-it.sh", "database:5432", "--", "./bootstrap.sh"]
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  database:
    image: postgres:latest
    hostname: database
    environment:
      - POSTGRES_PASSWORD=rinha_pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_rinha
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"